---
abstract: 'Adds gravatar images to rt'
author:
  - 'Christian Loos <cloos@netsandbox.de>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RT-Extension-Gravatar
no_index:
  directory:
    - html
    - inc
  package:
    - RT::User
requires:
  Crypt::SSLeay: 0
  perl: 5.8.3
resources:
  license: http://dev.perl.org/licenses/
version: 0.02
